site_name: 'python-app-5'
site_description: 'Main documentation for python-app-5'
repo_url: https://github.com/sukhsaggu/python-app-5
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'